version: '3'
services:
  backend-api:
    build: ./backend
    container_name: backend-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/music
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
    depends_on:
      - db
      - redis
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: music
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./sql/music.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    volumes:
      - ./redis/data:/data
      - ./redis/logs:/logs
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
